sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: myserver
    port: 3306
    database: sky_take_out
    username: root
    password: root
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  tencentoss:
    secret-id: AKIDoV0JOGuOehW9YjhRzKSN6b9TaVFl392j
    secret-key: WpxrY2LQHuJXXJsEMHzUpyucAGH1Yu2x
    bucket-name: nicebro-1309495005
    region: ap-guangzhou
    content-type: application/octet-stream

